services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///app.db
  test:
    build: .
    command: >
        sh -c "
          python -m doctest NPICalculator/controller.py -v; 
          python -m doctest NPICalculator/models.py -v;
          python -m doctest NPICalculator/views.py -v;
        "